version: '3.4'

services:
  tap.services.api:
    image: ${DOCKER_REGISTRY-}tapservicesapi
    build:
      context: .
      dockerfile: Tap.Services.Api/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    networks:
    - tap
    ports:
    - "7194:80"
    depends_on:
    - tap.sqlserver
    volumes:
    -  tap.api:/app/wwwroot
  tap.sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
    - "1433:1433"
    networks:
    - tap
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Password123
    volumes:  
    - tap.sqlserver:/var/opt/mssql 
    
volumes:
  tap.sqlserver:
  tap.api:

networks:
  tap:
    driver: bridge
