name: Publish to Azure Web App
on:
  workflow_dispatch:
  push:
    branches:
      - develop
env:
  AZURE_WEBAPP_NAME: foothill-tap
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - name: Restore dependencies
      run: dotnet restore ./tap.sln

    - name: Build
      run: dotnet build ./tap.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./tap.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: "${{ secrets.AZURE_PUBLISH_PROFILE }}"
